### ISSUE TITLE
Leeful900 GoldHEN v2.4b5 offline host

### ISSUE THREAD

**Issue by KXRIST** [KameleonReloaded/leeful900#3]
I am launching the local host and gets stuck to offline caching 33%. All Previous work fine (900v3,v4,v5).
IS there anything i have to do  ?

**Comment by Augusto101** [comment]
Exactly the same problem here...any clue what's going on?

**Comment by kmeps4** [comment]
Fixed and updated to GoldHEN v2.4b13
